name: app5
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^7.0.0  # ✅ UPDATE
  geolocator: ^14.0.2
  permission_handler: ^12.0.1  # ✅ UPDATE  
  vibration: ^3.1.4  # ✅ UPDATE
  flutter_local_notifications: ^19.5.0  # ✅ UPDATE
  audioplayers: ^5.2.1
  screen_state: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0  # ✅ UPDATE

flutter:
  uses-material-design: true

  assets:
    - assets/alert.mp3